platform :ios, '8.0'

target 'PodsHelloReact' do
  #use_frameworks!

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation-android'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end
